# Generated by Django 3.2.8 on 2021-10-24 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_uesr_id_post_uesr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='uesr',
            new_name='user',
        ),
    ]
